### ISSUE TITLE
Server & Client Service Compilation Docs

### ISSUE THREAD

**Issue by jonwinton** [clay/claycli#120]
A question came up about services for server/client and the following example of an error message:

```Error: A server-side only service must have a client-side counterpart (while requireTransform was processing /<PATH>/app/components/<COMPONENT>/model.js) while parsing file: /<PATH>/app/components/<COMPONENT>/model.js```

My quick explanation:

```So model.js files are isomorphic, but sometimes there are just better ways to do the same thing between the server and browser. Base64 encoding is one example, where the server uses Buffer and the browser has `atob/btoa`. So if a model.js file references a file in `services/server` it expects to be able to do that same thing in the browser and so during compilation we point to the `services/client` version of the server
If the service works in both environments then put it in `services/universal`
But it will only complain for dependencies of files being compiled```

I think it's better to talk about db interactions where on the server you have direct access to the db client and on the client you have to make HTTP requests

**Comment by oscarpolanco** [comment]
Hello @jonwinton. What you think?

The `model.js` is a [isomorphic](https://en.wikipedia.org/wiki/Isomorphic_JavaScript) file; this means that the first request is handled by the server
and the subsequent requests are handled by the client. So if we reference a file on the server we will expect to be able to do the same on the browser. 

An example will be the `Base64` encoding where a `Nodejs` server need to use the [Buffer](https://nodejs.org/api/buffer.html) on the browser it will need to use the [atob](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/atob)/[btoa](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa) functions.

In our case if the `model.js` reference a `services/server` file on the server then we will expect to do the same thing on the browser but in compilation time we point to the `services/client` version of the file but sometimes these files work on both environments we put in the `service/universal`. 

As a final example on the `model.js`, we can target directly to the database on the server but on the client, we need a different approach because we don't have the same ability as the server so we perform a request to obtain our data.

The error that originates this issue tell us that we have a reference to a `services/server` but doesn't have the `services/client` reference when compile.

**Comment by PedroAlbR** [comment]
@oscarpolanco I believe this is good, but it could improve a bit. Could you please open a PR with your suggestion so we can discuss there?

**Comment by oscarpolanco** [comment]
Thanks!!! I'm going to process with the new page that will have this info

**Comment by oscarpolanco** [comment]
Here is the [PR](https://github.com/clay/claycli/pull/151) that address this issue
