### ISSUE TITLE
ability to bulk import & publish only PUBLISHED pages

### ISSUE THREAD

**Issue by zonika** [clay/claycli#29]
I know the bulk import functionality is coming soon, but a big problem I've encountered using the scratch cli with the `--publish` flag is that it still tries to publish pages that are unpublished on the source clay instance. It would be nice if on clay-cli, one could:

1. publish a page on import (using a `--publish` flag or something)
2. only import articles that are published on the source instance when using the `--publish` flag (on a bulk page import)

**Comment by nelsonpecora** [comment]
Importing published pages should work correctly (once we've added that functionality), since claycli looks at the built-in `pages` index. This means that instead of doing a bunch of logic to try and determine if a page is published, it'll use that index as the source of truth. Ideally this should work for both single page import and full site (multi-page) import.

As for importing _only_ published stuff, that would break a lot of functionality (since the unpublished versions wouldn't exist, so you could never edit them and any API calls against them or their constituent components would 404)

**Comment by zonika** [comment]
Sorry, I didn't mean only import published instances of pages, but pages that _have_ published instances. This way, we aren't importing a bunch of unpublished and empty pages and attempting to publish them programmatically (like what scratch does now). Seems like this is what you plan to do anyway, so great!
