### ISSUE TITLE
CLI - Support Underscored Routes

### ISSUE THREAD

**Issue by pfeytser** [clay/claycli#47]

**Comment by nelsonpecora** [comment]
The fix for this is:

* use underscored routes by default
* add a `--amphora-version <integer>` flag
* if the amphora version is set to `4` (or lower), use non-underscored routes

(note: we're doing this, rather than a binary `--no-underscored-routes` flag, because the amphora api might change in future versions. this way, we'll be able to use `claycli` with multiple amphora versions without having to checkout different `claycli` versions, which is a hassle)

**Comment by nelsonpecora** [comment]
Actually, we'd need to split it into two flags anyway (it's possible to import from an old version of amphora to a new version), and this is a common enough use case that it should be fast to write. Thus, we should do:

* `--amphora-legacy, -a` use non-underscored api routes (applies like `--key`)
* `--source-amphora-legacy, -A` use non-underscored api routes (applies like `--source-key`)

**Comment by nelsonpecora** [comment]
We're actually going to handle this dynamically, but for now I've made a major version of claycli with hardcoded underscore support.
